# frozen_string_literal: true

require "rake/testtask"
require "bundler"
require "rbconfig"

EXAMPLE_APPLICATIONS = %w[blog store todomvc site wills_pizza workouts].freeze

Rake::TestTask.new do |task|
  task.libs << "test"
  task.pattern = "test/**/*_test.rb"
end

EXAMPLE_APPLICATIONS.each do |name|
  desc "Run the #{name} example tests with its own bundle"
  task "test:#{name}" do
    root = File.expand_path("examples/#{name}", __dir__)
    gemfile = File.join(root, "Gemfile")
    Bundler.with_unbundled_env do
      Dir.chdir(root) do
        sh({"BUNDLE_GEMFILE" => gemfile}, "bundle", "exec", "rake", "test")
      end
    end
  end
end

desc "Run every example application test suite"
task "test:examples" => EXAMPLE_APPLICATIONS.map { |name| "test:#{name}" }

desc "Run the JavaScript navigation tests"
task "test:client" do
  sh "npm run test:client"
end

desc "Run the browser navigation smoke tests"
task "test:browser" do
  sh "npm run test:browser"
end

desc "Verify the publishable Morpheus package and its vendored copies"
task "test:package" do
  sh "npm run test:package"
end

desc "Run the PostgreSQL portability contracts"
task "test:postgresql" do
  unless ENV["POSTGRES_DATABASE_URL"]
    abort "POSTGRES_DATABASE_URL is required (for example postgres://localhost/lunula_test)"
  end

  ruby "-Itest", "test/postgresql_contract_test.rb"
end

desc "Audit locked Ruby and npm dependencies"
task "test:audit" do
  sh "bundle-audit check"
  sh "npm audit --audit-level=high"
end

desc "Run all framework, example, client, browser, and dependency checks"
task check: [:test, "test:examples", "test:client", "test:browser", "test:package", "test:audit"]

namespace :release do
  desc "Validate the public API, release documentation, and release scripts"
  task :check do
    ruby "-Itest", "test/public_api_contract_test.rb"
    sh RbConfig.ruby, "-c", "script/generated_diff"
    sh RbConfig.ruby, "-c", "script/upgrade_test"
  end

  desc "Print generated-file changes from BASE_REF"
  task :generated_diff, [:base_ref] do |_task, arguments|
    base_ref = arguments[:base_ref] || abort("usage: rake release:generated_diff[BASE_REF]")
    sh RbConfig.ruby, "script/generated_diff", base_ref
  end

  desc "Test an application generated by BASE_REF against the current checkout"
  task :upgrade, [:base_ref] do |_task, arguments|
    base_ref = arguments[:base_ref] || abort("usage: rake release:upgrade[BASE_REF]")
    sh RbConfig.ruby, "script/upgrade_test", base_ref
  end
end

task default: :check
