source "https://rubygems.org"

gem "hacienda", path: "../.."
gem "puma", "~> 7.0"
gem "rake", "~> 13.2"
gem "rdoc", "~> 6.6"

group :test do
  gem "minitest", "~> 6.0"
  gem "rack-test", "~> 2.2"
end
