# frozen_string_literal: true

APP_ROOT = File.expand_path(__dir__) unless defined?(APP_ROOT)
require "hacienda"
require "rake/testtask"

Rake::TestTask.new do |task|
  task.libs << "test"
  task.pattern = "test/**/*_test.rb"
end

task default: :test
